<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">savePipelineToFilePost</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJX19pbnRlcmNlcHRlZFNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJfX2ludGVyY2VwdGVkU2VydmljZU5hbWUiICk7DQpJRGF0
YQlfX3BpcGVsaW5lID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBlbGluZUN1cnNvciwgIl9fcGlw
ZWxpbmUiICk7DQpJRGF0YQlfX2ludGVyY2VwdG9yU3RvcmFnZSA9IElEYXRhVXRpbC5nZXRJRGF0
YSggcGlwZWxpbmVDdXJzb3IsICJfX2ludGVyY2VwdG9yU3RvcmFnZSIgKTsNCmlmICggX19waXBl
bGluZSA9PSBudWxsKSB7DQoJX19waXBlbGluZSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsNCn0N
Ci8vIGdldCB0aGUgcmFuZG9tIElkIGZyb20gdGhlIF9faW50ZXJjZXB0b3JTdG9yYWdlIGlmIGEg
cHJlLXNlcnZpY2UgcHV0IGl0IGluDQpJbnRlZ2VyIHJhbmRvbUlkID0gcmFuZG9tLm5leHRJbnQo
KTsNCmlmKHJhbmRvbUlkIDwgMCApIHsNCglyYW5kb21JZCA9IHJhbmRvbUlkICogLTE7DQp9DQpp
ZiggX19pbnRlcmNlcHRvclN0b3JhZ2UgIT0gbnVsbCApIHsNCglyYW5kb21JZCA9IElEYXRhVXRp
bC5nZXRJbnQoX19pbnRlcmNlcHRvclN0b3JhZ2UuZ2V0Q3Vyc29yKCksICJyYW5kb21JZCIsIHJh
bmRvbUlkKTsNCn0gDQoNClN0cmluZyBmaWxlTmFtZSA9IF9faW50ZXJjZXB0ZWRTZXJ2aWNlTmFt
ZS5yZXBsYWNlRmlyc3QoIjoiLCAiIyIpICsgIl9wb3N0XyIgKyByYW5kb21JZCArICJfIiArIGZk
Zi5mb3JtYXQobmV3IGphdmEudXRpbC5EYXRlKCkpICsgIi54bWwiOw0KDQpzYXZlUGlwZWxpbmVU
b0ZpbGUoZmlsZU5hbWUsIF9fcGlwZWxpbmUpOw0KDQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
</value>
</Values>
