<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createTestFromCapturedPipelineDataWithXpath</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIHNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZS5nZXRDdXJz
b3IoKSwgInNlcnZpY2VOYW1lIik7DQpTdHJpbmcgcGFja2FnZU5hbWUgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKHBpcGVsaW5lLmdldEN1cnNvcigpLCAicGFja2FnZU5hbWUiKTsNClN0cmluZ1tdIHhw
YXRoQXJyID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KHBpcGVsaW5lLmdldEN1cnNvcigpLCAi
eHBhdGhBcnIiKTsNCmJvb2xlYW4gcmVtb3ZlUGlwZWxpbmVEYXRhID0gSURhdGFVdGlsLmdldEJv
b2xlYW4ocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJyZW1vdmVQaXBlbGluZURhdGEiLCBmYWxzZSk7
DQpTdHJpbmcgdGVzdFN1aXRlTmFtZVByZWZpeCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxp
bmUuZ2V0Q3Vyc29yKCksICJ0ZXN0U3VpdGVOYW1lUHJlZml4Iik7DQoNCmNvbS5zb2Z0d2FyZWFn
Lnd4LmlzLmludGVyY2VwdG9yLlRlc3RDYXNlQnVpbGRlciBidWlsZGVyID0gbmV3IGNvbS5zb2Z0
d2FyZWFnLnd4LmlzLmludGVyY2VwdG9yLlRlc3RDYXNlQnVpbGRlcigpOw0KdHJ5IHsNCglidWls
ZGVyLmNyZWF0ZVRlc3RDYXNlc0ZvclNlcnZpY2Uoc2VydmljZU5hbWUsIHBhY2thZ2VOYW1lLCBy
ZW1vdmVQaXBlbGluZURhdGEsIHhwYXRoQXJyLCB0ZXN0U3VpdGVOYW1lUHJlZml4KTsNCn0gY2F0
Y2goRXhjZXB0aW9uIGUpIHsNCgllLnByaW50U3RhY2tUcmFjZSgpOw0KCXRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKCJDb3VsZCBub3QgY3JlYXRlIHRlc3QgY2FzZXM6ICIgKyBlKTsNCn0=</value>
</Values>
