<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createTestFromCapturedPipelineData</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIHNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZS5nZXRDdXJz
b3IoKSwgInNlcnZpY2VOYW1lIik7DQpTdHJpbmcgcGFja2FnZU5hbWUgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKHBpcGVsaW5lLmdldEN1cnNvcigpLCAicGFja2FnZU5hbWUiKTsNCmJvb2xlYW4gcmVt
b3ZlUGlwZWxpbmVEYXRhID0gSURhdGFVdGlsLmdldEJvb2xlYW4ocGlwZWxpbmUuZ2V0Q3Vyc29y
KCksICJyZW1vdmVQaXBlbGluZURhdGEiLCBmYWxzZSk7DQpTdHJpbmcgdGVzdFN1aXRlTmFtZVBy
ZWZpeCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJ0ZXN0U3Vp
dGVOYW1lUHJlZml4Iik7DQoNCmNvbS5zb2Z0d2FyZWFnLnd4LmlzLmludGVyY2VwdG9yLnRlc3Ri
dWlsZGVyLlRlc3RDYXNlQnVpbGRlciBidWlsZGVyID0gbmV3IGNvbS5zb2Z0d2FyZWFnLnd4Lmlz
LmludGVyY2VwdG9yLnRlc3RidWlsZGVyLlRlc3RDYXNlQnVpbGRlcigpOw0KdHJ5IHsNCmJ1aWxk
ZXIuY3JlYXRlVGVzdENhc2VzRm9yU2VydmljZShzZXJ2aWNlTmFtZSwgcGFja2FnZU5hbWUsIHJl
bW92ZVBpcGVsaW5lRGF0YSwgdGVzdFN1aXRlTmFtZVByZWZpeCk7DQp9IGNhdGNoKEV4Y2VwdGlv
biBlKSB7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkNvdWxkIG5vdCBjcmVhdGUgdGVz
dCBjYXNlczogIiArIGUpOw0KfQ==</value>
</Values>
