<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createTestFromCapturedPipelineDataWithXpath</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIHNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZS5nZXRDdXJz
b3IoKSwgInNlcnZpY2VOYW1lIik7DQpTdHJpbmcgcGFja2FnZU5hbWUgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKHBpcGVsaW5lLmdldEN1cnNvcigpLCAicGFja2FnZU5hbWUiKTsNClN0cmluZ1tdIHhw
YXRoQXJyID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KHBpcGVsaW5lLmdldEN1cnNvcigpLCAi
eHBhdGhBcnIiKTsNCmJvb2xlYW4gcmVtb3ZlUGlwZWxpbmVEYXRhID0gSURhdGFVdGlsLmdldEJv
b2xlYW4ocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJyZW1vdmVQaXBlbGluZURhdGEiLCBmYWxzZSk7
DQpTdHJpbmcgdGVzdFN1aXRlTmFtZVByZWZpeCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxp
bmUuZ2V0Q3Vyc29yKCksICJ0ZXN0U3VpdGVOYW1lUHJlZml4Iik7DQoNCmNvbS5zb2Z0d2FyZWFn
Lnd4LmlzLmludGVyY2VwdG9yLnRlc3RidWlsZGVyLlRlc3RDYXNlQnVpbGRlciBidWlsZGVyID0g
bmV3IGNvbS5zb2Z0d2FyZWFnLnd4LmlzLmludGVyY2VwdG9yLnRlc3RidWlsZGVyLlRlc3RDYXNl
QnVpbGRlcigpOw0KdHJ5IHsNCglidWlsZGVyLmNyZWF0ZVRlc3RDYXNlc0ZvclNlcnZpY2Uoc2Vy
dmljZU5hbWUsIHBhY2thZ2VOYW1lLCByZW1vdmVQaXBlbGluZURhdGEsIHhwYXRoQXJyLCB0ZXN0
U3VpdGVOYW1lUHJlZml4KTsNCn0gY2F0Y2goRXhjZXB0aW9uIGUpIHsNCgllLnByaW50U3RhY2tU
cmFjZSgpOw0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJDb3VsZCBub3QgY3JlYXRlIHRl
c3QgY2FzZXM6ICIgKyBlKTsNCn0=</value>
</Values>
