<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">savePipelineForRestorePre</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJX19pbnRlcmNlcHRlZFNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJfX2ludGVyY2VwdGVkU2VydmljZU5hbWUiICk7DQoNCi8v
IF9fcGlwZWxpbmUNCklEYXRhCV9fcGlwZWxpbmUgPSBJRGF0YVV0aWwuZ2V0SURhdGEoIHBpcGVs
aW5lQ3Vyc29yLCAiX19waXBlbGluZSIgKTsNCmlmKCBfX2ludGVyY2VwdGVkU2VydmljZU5hbWUg
PT0gbnVsbCApIHsNCglTeXN0ZW0ub3V0LnByaW50bG4oIl9faW50ZXJjZXB0ZWRTZXJ2aWNlTmFt
ZSBpcyBudWxsIik7DQp9DQppZiAoIF9fcGlwZWxpbmUgIT0gbnVsbCkgew0KCVN0cmluZyBzZXJ2
aWNlTmFtZSA9ICB0cmFuc2Zvcm1TZXJ2aWNlTmFtZShfX2ludGVyY2VwdGVkU2VydmljZU5hbWUp
Ow0KCVN0cmluZyBmaWxlTmFtZSA9IHNlcnZpY2VOYW1lICsgIl9waXBlbGluZUZvclJlc3RvcmVf
IiArICJfIiArIGZkZi5mb3JtYXQobmV3IGphdmEudXRpbC5EYXRlKCkpICsgIi54bWwiOw0KCXNh
dmVQaXBlbGluZVRvRmlsZShmaWxlTmFtZSwgX19waXBlbGluZSk7DQoJDQoJLy8gYWRkIHRoZSBy
YW5kb20gSWQgdG8gdGhlIF9faW50ZXJjZXB0b3JTdG9yYWdlIHNvIHRoYXQgYSBwb3N0IHNlcnZp
Y2UgY2FuIHBpY2sgaXQgdXANCglJRGF0YQlfX2ludGVyY2VwdG9yU3RvcmFnZSA9IElEYXRhRmFj
dG9yeS5jcmVhdGUoKTsNCn0NCi8vIHBpcGVsaW5lDQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1
cnNvciwgIl9fY2FuY2VsU2VydmljZUludm9jYXRpb24iLCAidHJ1ZSIgKTsNCg0KSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJfX3BpcGVsaW5lIiwgX19waXBlbGluZSApOw0KcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KDQoJ</value>
</Values>
